### ISSUE TITLE
User Story 8 - Packing list Edit

### ISSUE THREAD

**Issue by miriam-ertl** [miriam-ertl/weather-and-activities-app#5]
## Value proposition

**As a** user
**I want to** be able to click on checkboxes
**so that** I can control what I've already packed

## Description

![Image](https://github.com/miriam-ertl/weather-and-activities-app/assets/128323709/ef1965f5-c1e3-41ae-b358-c7c2a9cae848)

## Acceptance criteria

- [ ] Left beside each item is a checkbox
- [ ] A checkbox can be clicked when the item is packed 
- [ ] Clicking on a checkbox the item will be crossed out and it is checked  
- [ ] By unchecking an item it will be uncrossed again

## Tasks

- [ ] Create the feature branch `feature/packing-list-Edit`
- [ ] Add a checkbox to each list item
- [ ] The checkbox has two values: checked and unchecked 

```
